repfinder/config/routes.rb
Repfinder::Application.routes.draw do

  root 'repfinder#index'

  match 'repfinder', to: 'repfinder#create', as: 'find_rep', via: 'POST'

  get 'repfinder/:zipcode', to: 'repfinder#show', as: 'show_rep'

end

repfinder/app/models/congress_fetcher.rb
require 'uri'
require 'json'

class CongressFetcher 

  def fetch(zipcode)
    @zipcode = zipcode
    response = Faraday.get("http://localhost:4000/congressmen/#{@zipcode}")
    JSON.parse(response.body)
  end

end

repfinder/app/models/zipcode.rb
class Zipcode
  include ActiveModel::Model 
  attr_accessor :zipcode  

  

end

repfinder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

repfinder/app/controllers/repfinder_controller.rb
class RepfinderController < ApplicationController

  def index
    @zipcode = Zipcode.new
  end

  def show
    c = CongressFetcher.new
    @reps = c.fetch(params[:zipcode])
  end

  def create
    redirect_to show_rep_path(:zipcode => params[:zipcode]["zipcode"])
  end

end

repfinder/app/helpers/application_helper.rb
module ApplicationHelper
end

repfinder/app/helpers/rep_finder_helper.rb
module RepFinderHelper
end

repfinder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Repfinder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

repfinder/app/views/repfinder/index.html.erb
<%# form_for :zipcode, :url => { action: 'create', zipcode: @zipcode} do |f| %>

<%= form_for @zipcode, :url => find_rep_path, :html => {:method => :post} do |f| %>

  <%= f.label :zipcode %>:
  <%= f.text_field :zipcode %>

  <%= f.submit "Submit" %>

<% end %>

repfinder/app/views/repfinder/show.html.erb
<%= @reps %>